# Generated by Django 6.0.7 on 2026-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/profile/'),
        ),
    ]
