# Generated by Django 6.0.7 on 2026-07-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_kycprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
