# Generated by Django 6.0.7 on 2026-07-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shippingaddress'),
        ('vendors', '0007_alter_vendorchatsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.city'),
        ),
    ]
