# Generated by Django 6.0.7 on 2026-07-26 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformannouncement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('BUYERS', 'Only Buyers'), ('VENDORS', 'Only Vendors'), ('SERVICE_PROVIDERS', 'Only Service Providers'), ('STAFF', 'Only Staff'), ('SPECIFIC_USERS', 'Specific Users')], default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specific_targets', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PlatformAnnouncement',
        ),
    ]
