# Generated by Django 6.0.7 on 2026-07-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_broadcastannouncement_delete_platformannouncement'),
        ('products', '0007_remove_category_commission_rate'),
        ('services', '0014_remove_servicecategory_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission in percentage (%)', max_digits=5)),
                ('flat', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat commission amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='products.category')),
                ('servicecategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='services.servicecategory')),
            ],
        ),
    ]
