# Generated by Django 6.0.7 on 2026-07-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_businessprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='icon',
            new_name='icon_img',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
