# Generated by Django 6.0.7 on 2026-07-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_icon_servicecategory_icon_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='longitude',
        ),
    ]
