# Generated by Django 6.0.7 on 2026-07-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_businessprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='is_verified',
        ),
    ]
