# Generated by Django 6.0.7 on 2026-07-16 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_businessprofile_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessProfile',
            new_name='ServiceProviderBusinessProfile',
        ),
    ]
