# Generated by Django 6.0.7 on 2026-07-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_chatmessage_options_remove_chatmessage_booking_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='services_ch_session_87aa1d_idx',
        ),
        migrations.RenameField(
            model_name='servicebooking',
            old_name='problem_description',
            new_name='service_description',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='attachment',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('SYSTEM_ALERT', 'System Alert'), ('INVOICE', 'Invoice')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='chat_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_booking', to='services.chatsession'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Provider Approval'), ('CONFIRMED', 'Confirmed & Coming'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
    ]
