# Generated by Django 6.0.7 on 2026-07-21 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_chatmessage_services_ch_session_87aa1d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderNotification',
            new_name='ServiceProviderNotification',
        ),
        migrations.RenameModel(
            old_name='ProviderReview',
            new_name='ServiceProviderReview',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='buyer_latitude',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='buyer_longitude',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_number',
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_charges_note', models.TextField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('CARD', 'Credit/Debit Card')], max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='services.servicebooking')),
            ],
        ),
    ]
