# Generated by Django 6.0.7 on 2026-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_providernotification_serviceprovidernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderreview',
            name='behavior_rating',
        ),
        migrations.RemoveField(
            model_name='serviceproviderreview',
            name='price_fairness',
        ),
        migrations.RemoveField(
            model_name='serviceproviderreview',
            name='response_time_rating',
        ),
        migrations.AddField(
            model_name='serviceproviderreview',
            name='bill_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='serviceproviderreview',
            name='honesty_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='serviceproviderreview',
            name='on_time_delivery_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='serviceproviderreview',
            name='response_and_behavior_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='serviceproviderreview',
            name='rating_stars',
            field=models.FloatField(default=5.0),
        ),
    ]
