# Generated by Django 6.0.7 on 2026-07-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_serviceproviderreview_behavior_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='platform_commission',
        ),
    ]
