# Generated by Django 6.0.7 on 2026-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_serviceproviderbusinessprofile_admin_rating_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage commission (e.g., 5.00 for 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated commission amount', max_digits=10),
        ),
    ]
