# Generated by Django 6.0.7 on 2026-07-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicecategory_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='platform_commission',
        ),
    ]
