# Generated by Django 6.0.7 on 2026-07-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_servicecategory_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinvoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='PAID', max_length=30),
        ),
    ]
