# Generated by Django 6.0.7 on 2026-07-29 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_servicecommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderbusinessprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderbusinessprofile',
            name='available_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderbusinessprofile',
            name='total_complete_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceproviderbusinessprofile',
            name='work_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Recentwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/recent_works/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_works', to='services.serviceproviderbusinessprofile')),
            ],
        ),
    ]
