# Generated by Django 6.0.7 on 2026-07-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_globalchatsession_globalchatmessage"),
        ("services", "0017_serviceproviderbusinessprofile_about_me_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatsession",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="provider",
        ),
        migrations.AlterField(
            model_name="servicebooking",
            name="chat_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_booking",
                to="core.globalchatsession",
            ),
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatSession",
        ),
    ]
