# Generated by Django 6.0.7 on 2026-07-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='shop_slug',
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_type',
            field=models.CharField(choices=[('RETAILER', 'Retailer'), ('WHOLESALER', 'Wholesaler')], default='RETAILER', max_length=20),
        ),
    ]
