# Generated by Django 6.0.7 on 2026-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_shopprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopreview',
            name='behavior_rating',
        ),
        migrations.RemoveField(
            model_name='shopreview',
            name='delivery_rating',
        ),
        migrations.AddField(
            model_name='shopreview',
            name='on_time_delivery_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='shopreview',
            name='response_and_behavior_rating',
            field=models.IntegerField(default=5),
        ),
    ]
