# Generated by Django 6.0.7 on 2026-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorchatsession_vendorchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='admin_rating_adjustment',
            field=models.FloatField(default=0.0, help_text='Manual rating adjustment by admin'),
        ),
    ]
