# Generated by Django 6.0.7 on 2026-07-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_city_shopprofile_city"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vendorchatsession",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vendorchatsession",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="vendorchatsession",
            name="vendor",
        ),
        migrations.DeleteModel(
            name="VendorChatMessage",
        ),
        migrations.DeleteModel(
            name="VendorChatSession",
        ),
    ]
