# Generated by Django 6.0.7 on 2026-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0007_alter_vendorchatsession_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopprofile",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
