# Generated by Django 6.0.7 on 2026-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='applied_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate applied at the time of order', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated commission amount for this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='courier_name',
            field=models.CharField(blank=True, help_text='Courier service used for delivery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Courier tracking ID', max_length=100, null=True),
        ),
    ]
