# Generated by Django 6.0.7 on 2026-07-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_applied_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='applied_commission_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='vendororder',
            name='courier_name',
        ),
        migrations.RemoveField(
            model_name='vendororder',
            name='tracking_id',
        ),
    ]
