# Generated by Django 6.0.7 on 2026-07-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_applied_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_dhaka', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outside_dhaka', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Delivery Charges',
            },
        ),
    ]
