# Generated by Django 6.0.7 on 2026-07-27 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
