# Generated by Django 6.0.7 on 2026-07-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverycharge_created_at_deliverycharge_updated_at'),
        ('vendors', '0006_city_shopprofile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycharge',
            old_name='inside_dhaka',
            new_name='inside_city',
        ),
        migrations.RenameField(
            model_name='deliverycharge',
            old_name='outside_dhaka',
            new_name='outside_city',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_ADMIN_APPROVAL', 'Pending Admin Approval'), ('APPROVED', 'Approved (Sent to Vendor)'), ('REJECTED', 'Rejected')], default='PENDING_ADMIN_APPROVAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='vendor_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='vendors.shopprofile'),
        ),
    ]
