# Generated by Django 6.0.7 on 2026-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordercommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercommission',
            name='applied_flat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordercommission',
            name='applied_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
