# Generated by Django 6.0.7 on 2026-08-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_chatsessioninvoice_chatsessioninvoicecommission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsessioninvoice',
            name='after_discount_price',
        ),
        migrations.RemoveField(
            model_name='chatsessioninvoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='chatsessioninvoice',
            name='price_per_one_pice',
        ),
        migrations.RemoveField(
            model_name='chatsessioninvoice',
            name='quantity',
        ),
    ]
