# Generated by Django 6.0.7 on 2026-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_sku_alter_product_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage commission (e.g., 5.00 for 5%)', max_digits=5),
        ),
    ]
