# Generated by Django 6.0.7 on 2026-07-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='commission_rate',
        ),
    ]
