# Generated by Django 6.0.7 on 2026-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_category_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], default='RETAIL', max_length=20),
        ),
    ]
