# Generated by Django 6.0.7 on 2026-07-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_type',
            new_name='category_type',
        ),
    ]
