# Generated by Django 6.0.7 on 2026-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_product_type_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Size of the product (e.g., M, L, XL, 42, 44)', max_length=50, null=True),
        ),
    ]
